### ISSUE TITLE
Wii U Save Support ?

### ISSUE THREAD

**Issue by Mollomm1** [kbinani/je2be-desktop#2]
Do you plan adding Minecraft Wii U save support?

**Comment by kbinani** [comment]
@Mollomm1 No, not planned. Because the conversion from Java/Bedrock to Wii U requires downgrading the game data to something legacy form, and it's not included in je2be (This is intentional to keep the code simple).

**Comment by wendellmeset** [comment]
@Mollomm1 use mcctoolchest console (the one on the weebly website) to convert your world to java or bedrock if you still want to convert to wii-u, I recommend converting it to java cause that is what is best supported during console conversions overall and with mcc tool chest, then use this (je2be [desktop]) to convert that java world to bedrock if needed!
