### ISSUE TITLE
Multiplatform

### ISSUE THREAD

**Issue by wendellmeset** [kbinani/je2be-desktop#5]
As per common app development, and the fact that je2be supports java edition, I believe you should create mac and linux releases of the software, while this is already one of the most platform friendly apps ever, having web, windows, and IOS support. It lacks Android, Linux, and Mac support, android is less important as of now however it would be nice to see some native desktop apps for linux and mac! I am pretty sure CMake can compile to them, at least to Linux I believe, and maybe Mac!

**Comment by kbinani** [comment]
There are currently no plans to add support platforms other than Windows, iOS, and web
